galaxy_uid: 10010
galaxy_gid: 10010

use_internal_ips: true

# Monitoring
telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["{{ grafana_server_url }}"]
      - database = "aarnet"
      - precision = "s"