auth_key_user: ubuntu

head_nodes: "{{ groups['aarnet_slurm_head'] }}"
worker_nodes: "{{ groups['aarnet_workers'] }}"
galaxy_nodes: "{{ groups['aarnet_galaxy_server'] }}"

add_galaxy_user: true # Adds the galaxy user to all machines that have slurm on them

# SLURM
slurm_nodes:
  - name: aarnet-w1
    NodeAddr: "{{ hostvars['aarnet-w1']['internal_ip'] }}"
    CPUs: 16
    RealMemory: 62815
    State: UNKNOWN
  - name: aarnet-w2
    NodeAddr: "{{ hostvars['aarnet-w2']['internal_ip'] }}"
    CPUs: 16
    RealMemory: 62815
    State: UNKNOWN
  - name: aarnet-w3
    NodeAddr: "{{ hostvars['aarnet-w3']['internal_ip'] }}"
    CPUs: 16
    RealMemory: 62815
    State: UNKNOWN
  - name: aarnet-w4
    NodeAddr: "{{ hostvars['aarnet-w4']['internal_ip'] }}"
    CPUs: 16
    RealMemory: 62815
    State: UNKNOWN
  - name: aarnet-w5
    NodeAddr: "{{ hostvars['aarnet-w5']['internal_ip'] }}"
    CPUs: 16
    RealMemory: 62815
    State: UNKNOWN
  - name: aarnet-w6
    NodeAddr: "{{ hostvars['aarnet-w6']['internal_ip'] }}"
    CPUs: 32
    RealMemory: 125812
    State: UNKNOWN
  - name: aarnet-w7
    NodeAddr: "{{ hostvars['aarnet-w7']['internal_ip'] }}"
    CPUs: 16
    RealMemory: 62815
    State: UNKNOWN
  - name: aarnet-w8
    NodeAddr: "{{ hostvars['aarnet-w8']['internal_ip'] }}"
    CPUs: 16
    RealMemory: 62815
    State: UNKNOWN
  - name: aarnet-w9
    NodeAddr: "{{ hostvars['aarnet-w9']['internal_ip'] }}"
    CPUs: 32
    RealMemory: 125812
    State: UNKNOWN
  - name: aarnet-w10
    NodeAddr: "{{ hostvars['aarnet-w10']['internal_ip'] }}"
    CPUs: 32
    RealMemory: 125812
    State: UNKNOWN
  - name: aarnet-queue
    NodeAddr: "{{ hostvars['aarnet-queue']['internal_ip'] }}"
    CPUs: 4
    RealMemory: 15638
    State: UNKNOWN
  - name: aarnet
    NodeAddr: "{{ hostvars['aarnet']['internal_ip'] }}"
    CPUs: 16
    RealMemory: 62815
    State: UNKNOWN

slurm_partitions:
  - name: main
    nodes: "aarnet-w1,aarnet-w2,aarnet-w3,aarnet-w4,aarnet-w5,aarnet-w6,aarnet-w8,aarnet-w9,aarnet-w10"
    Default: YES
    State: UP
  - name: training
    nodes: "aarnet-w7,aarnet-w5,aarnet-w4,aarnet-w8,aarnet-w10"
    Default: NO
    State: UP
  - name: interactive_tools
    nodes: "aarnet-w4,aarnet-w5"
    Default: NO
    State: UP
    MaxTime: "10:00:00"

slurm_controller_host: aarnet-queue

slurm_munge_key: files/keys/munge.key
