galaxy_uid: 10010
galaxy_gid: 10010

use_internal_ips: true

influx_url: stats.usegalaxy.org.au
grafana_server_url: "https://{{ influx_url }}:8086"

install_python_311: True

# Monitoring
telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["{{ grafana_server_url }}"]
      - database = "galaxy_etca"
      - precision = "s"
      - username = "node"
      - password = "{{ vault_influx_node_password }}"

# dbservers and galaxyservers
galaxy_db_user_password: "{{ vault_galaxy_db_user_password }}"
galaxy_db_reader_password: "{{ vault_galaxy_db_reader_password }}"
galaxy_db_tiaasadmin_password: "{{ vault_galaxy_db_tiaasadmin_password }}"
galaxy_db_tiaas_password: "{{ vault_galaxy_db_tiaas_password }}"

# qld_file_mounts_available: set to true if /mnt/files, /mnt/files2 should be in the object store
qld_file_mounts_available: True # assume true unless set to false
pawsey_file_mounts_available: True # assume true unless set to false

qld_file_mounts_path: /mnt/user-data-qld
pawsey_file_mounts_path: /mnt/user-data-pawsey

galaxy_user_data_nfs_opts: 'noatime,defaults'

galaxy_server_and_worker_shared_mounts: # Everything mounted on galaxy, galaxy_handlers and workers
  # scratch server: the new home of job working directories (May 2024)
  - path: /mnt/scratch
    src: nsw-etca-pfnfs1.aarnet.net.au:/data/galaxy/scratch
    opts: proto=tcp,noatime
    fstype: nfs
    state: mounted
  # galaxy-misc-nfs
  - path: /mnt/tools
    src: "{{ hostvars['galaxy-misc-nfs']['internal_ip'] }}:/mnt/tools"
    fstype: nfs
    opts: 'noatime,defaults'
    state: mounted
  - path: /mnt/custom-indices
    src: "{{ hostvars['galaxy-misc-nfs']['internal_ip'] }}:/mnt/custom-indices"
    fstype: nfs
    state: mounted
  # galaxy-job-nfs
  - path: /mnt/tmp
    src: "{{ hostvars['galaxy-job-nfs']['internal_ip'] }}:/mnt/tmp"
    fstype: nfs
    state: mounted
    opts: 'noatime,defaults'
  # galaxy-user-nfs
  - path: /mnt/user-data-volA # 150T volume
    src: "{{ hostvars['galaxy-user-nfs']['internal_ip'] }}:/mnt/volA"
    fstype: nfs
    opts: "{{ galaxy_user_data_nfs_opts }}"
    state: mounted
  - path: /mnt/user-data-volB # 50T volume
    src: "{{ hostvars['galaxy-user-nfs']['internal_ip'] }}:/mnt/volB"
    fstype: nfs
    opts: "{{ galaxy_user_data_nfs_opts }}"
    state: mounted
  - path: /mnt/user-data-volC # 42T volume
    src: "{{ hostvars['galaxy-user-nfs']['internal_ip'] }}:/mnt/volC"
    fstype: nfs
    opts: "{{ galaxy_user_data_nfs_opts }}"
    state: mounted
  # pawsey data volumes
  - path: "{{ pawsey_file_mounts_path }}/user-data"
    src: "pawsey-user-nfs.usegalaxy.org.au:/mnt/user-data"
    fstype: nfs
    opts: 'noatime,defaults'
    state: "{{ 'mounted' if pawsey_file_mounts_available else 'absent_from_fstab' }}"
  - path: "{{ pawsey_file_mounts_path }}/user-data-2"
    src: "pawsey-user-nfs.usegalaxy.org.au:/user-data-2"
    fstype: nfs
    opts: 'noatime,defaults'
    state: "{{ 'mounted' if pawsey_file_mounts_available else 'absent_from_fstab' }}"
  - path: "{{ pawsey_file_mounts_path }}/user-data-3"
    src: "pawsey-user-nfs.usegalaxy.org.au:/user-data-3"
    fstype: nfs
    opts: 'noatime,defaults'
    state: "{{ 'mounted' if pawsey_file_mounts_available else 'absent_from_fstab' }}"
  - path: "{{ pawsey_file_mounts_path }}/user-data-4"
    src: "pawsey-user-nfs.usegalaxy.org.au:/user-data-4"
    fstype: nfs
    opts: 'noatime,defaults'
    state: "{{ 'mounted' if pawsey_file_mounts_available else 'absent_from_fstab' }}"
  # QLD data volumes
  - path: "{{ qld_file_mounts_path }}/files"
    src: "galaxy-aust-exports.genome.edu.au:/Q0028_files"
    fstype: nfs
    opts: 'noatime,defaults'
    state: "{{ 'mounted' if qld_file_mounts_available else 'absent_from_fstab' }}"
  - path: "{{ qld_file_mounts_path }}/files2"
    src: "galaxy-aust-exports.genome.edu.au:/mnt/files2"
    fstype: nfs
    opts: 'noatime,defaults'
    state: "{{ 'mounted' if qld_file_mounts_available else 'absent_from_fstab' }}"

galaxy_worker_mounts:
  - path: /mnt/galaxy
    src: "{{ hostvars['galaxy-misc-nfs']['internal_ip'] }}:/mnt/ghost-galaxy-app"
    fstype: nfs
    opts: 'noatime,defaults'
    state: mounted

galaxy_web_server_mounts:
  - path: /mnt/ghost-galaxy-app
    src: "{{ hostvars['galaxy-misc-nfs']['internal_ip'] }}:/mnt/ghost-galaxy-app"
    fstype: nfs
    opts: 'noatime,defaults'
    state: mounted
