
auth_key_user: ubuntu

head_nodes: "{{ groups['pawsey_slurm_head'] }}"
worker_nodes: "{{ groups['pawsey_workers'] }}"
galaxy_nodes: "{{ groups['pawsey_galaxy_server'] }}"

add_galaxy_user: true #Adds the galaxy user to all machines that have slurm on them

# SLURM
slurm_nodes:
    - name: pawsey-w1
      NodeAddr: "{{ hostvars['pawsey-w1']['internal_ip'] }}"
      CPUs: 16
      RealMemory: 62815
      State: UNKNOWN
    - name: pawsey-w2
      NodeAddr: "{{ hostvars['pawsey-w2']['internal_ip'] }}"
      CPUs: 16
      RealMemory: 62815
      State: UNKNOWN
    - name: pawsey-w3
      NodeAddr: "{{ hostvars['pawsey-w3']['internal_ip'] }}"
      CPUs: 16
      RealMemory: 62815
      State: UNKNOWN
    - name: pawsey-w4
      NodeAddr: "{{ hostvars['pawsey-w4']['internal_ip'] }}"
      CPUs: 16
      RealMemory: 62815
      State: UNKNOWN
    - name: pawsey-w5
      NodeAddr: "{{ hostvars['pawsey-w5']['internal_ip'] }}"
      CPUs: 16
      RealMemory: 62815
      State: UNKNOWN
    - name: pawsey-w6
      NodeAddr: "{{ hostvars['pawsey-w6']['internal_ip'] }}"
      CPUs: 32
      RealMemory: 125812
      State: UNKNOWN
    - name: pawsey-w7
      NodeAddr: "{{ hostvars['pawsey-w7']['internal_ip'] }}"
      CPUs: 16
      RealMemory: 62815
      State: UNKNOWN
    - name: pawsey-w8
      NodeAddr: "{{ hostvars['pawsey-w8']['internal_ip'] }}"
      CPUs: 16
      RealMemory: 62815
      State: UNKNOWN
    - name: pawsey-queue
      NodeAddr: "{{ hostvars['pawsey-queue']['ansible_ssh_host'] }}"
      CPUs: 4
      RealMemory: 15638
      State: UNKNOWN
    - name: pawsey
      NodeAddr: "{{ hostvars['pawsey']['ansible_ssh_host'] }}"
      CPUs: 16
      RealMemory: 62815
      State: UNKNOWN

slurm_partitions:
    - name: main
      nodes: "pawsey-w1,pawsey-w2,pawsey-w3,pawsey-w4,pawsey-w5,pawsey-w6"
      Default: YES
      State: UP
    - name: training
      nodes: "pawsey-w7,pawsey-w5,pawsey-w4,pawsey-w8"
      Default: NO
      State: UP
    - name: max_quant_w8
      nodes: "pawsey-w8,pawsey-w3"
      Default: NO
      State: UP
    - name: interactive_tools
      nodes: "pawsey-w4,pawsey-w5"
      Default: NO
      State: UP
      MaxTime: '10:00:00'
    

slurm_config:
    #SlurmDBd includes
    AccountingStorageType: accounting_storage/slurmdbd
    AccountingStorageHost: localhost
    JobAcctGatherType: jobacct_gather/linux
    ControlMachine: pawsey-queue
    SlurmctldPidFile: /run/slurmctld.pid
    SlurmdPidFile: /run/slurmd.pid
    # SCHEDULING
    FastSchedule: 2
    SchedulerType: sched/backfill
    SelectType: select/cons_res
    SelectTypeParameters: CR_CPU_Memory,CR_LLN

slurm_munge_key: files/keys/munge.key
