pulsar_queue_url: "galaxy-queue.usegalaxy.org.au"

attached_volumes:
  - device: /dev/nvme0n1
    partition: 1
    path: /mnt
    fstype: ext4

shared_mounts:
  - src: "{{ hostvars['qld-ref-nfs'].ansible_ssh_host }}:/mnt/vdb/alphafold_db"
    path: /data/alphafold_databases/2.3
    fstype: nfs
    state: mounted

galaxy_uid: 10010
galaxy_gid: 10010

use_internal_ips: false

# cvmfs
cvmfs_cache_base: /mnt/var/lib/cvmfs
cvmfs_quota_limit: 20000

#Monitoring for Staging. Once all VM monitoring has moved to stats.usegalaxy.org.au, this can be put in all.yml and removed here.
influx_url: stats.usegalaxy.org.au
grafana_server_url: "https://{{ influx_url }}:8086"

# Monitoring
telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["{{ grafana_server_url }}"]
      - database = "pulsar-special"
      - precision = "s"
      - username = "node"
      - password = "{{ vault_influx_node_password }}"

auth_key_user: ubuntu

head_nodes: "{{ groups[ansible_hostname] }}"

# Use mamba as replacement for conda
pulsar_conda_exec: "mamba"

# SLURM
slurm_nodes:
    - name: "{{ ansible_hostname }}"
      NodeAddr: "{{ hostvars[ansible_hostname]['ansible_ssh_host'] }}"
      CPUs: 64
      RealMemory: 596400
      State: UNKNOWN
      Gres: gpu:1

slurm_partitions:
    - name: main
      nodes: "{{ ansible_hostname }}"
      Default: YES
      MaxTime: INFINITE
      State: UP

slurm_controller_host: "{{ ansible_hostname }}"

host_slurm_config:
    GresTypes: gpu

slurm_gres_config:
    - NodeName: "{{ ansible_hostname }}"
      Name: gpu
      Count: 1
      Type: nvidia
      File: /dev/nvidia0

slurm_munge_key: files/keys/munge.key

extra_keys:
  - id: ubuntu_maintenance_key
    type: public
    from: "{{ hostvars['galaxy']['ansible_ssh_host'] }},{{ hostvars['galaxy-handlers']['ansible_ssh_host'] }},{{ hostvars['galaxy-backup']['ansible_ssh_host'] }}"

# docker
docker_daemon_options:
  data-root: /mnt/docker-data
