toolmsg_messages:

# - tool_id: to match subject.startsWith(tool_id)
#            Best to use remove version numbers and trailing slash
#            e.g. toolshed.g2.bx.psu.edu/repos/galaxyp/diann/diann
#   message: A custom HTML message to be displayed for this tool
#   class: bootstrap class [primary, info, success, warning, danger]

  - tool_id: toolshed.g2.bx.psu.edu/repos/galaxyp/diann/diann
    message: >
      Access rights to this tool have changed, please
      <a href="https://site.usegalaxy.org.au/request/access/diann"
         target="_blank"
      >
        apply for access
      </a>
      to continue using this tool.
    class: warning

  - tool_id: toolshed.g2.bx.psu.edu/repos/galaxy-australia/alphafold2/alphafold
    message: >
      This tool has been updated in line with best practice recommendations. <a href="https://site.usegalaxy.org.au/notice/32" target="_blank">Click for more information.</a>
    class: info

  - tool_id: toolshed.g2.bx.psu.edu/repos/iuc/ena_upload/ena_upload
    message: >
      Please note, this upload tool is suitable for small datasets only and may not perform well for
      <strong>datasets that exceed several GB</strong>.
      Please contact
      <a href="mailto:help@genome.edu.au">help@genome.edu.au</a>
      for support on how to move large datasets.
    class: info
