#paths

script_path: ~/galaxy_backup
backup_path: ~/galaxy-backups

use_swift: false
use_slack: false

swift_backup_container: ""
swift_cred_file: ""
venv_location: "{{ script_path }}/venv"

#The name of the database to backup
psql_db: 'galaxy'

#Database connection vars
db_user: galaxy
db_password: ""
db_server: localhost
db_port: 5432

# Retention time variables
monthly_backup_day: 1  #Monthly backups will run on this day of the month
weekly_backup_day: 6  #Weekly backups will run on this day of the week
retention_day: 6       #Keep daily backups for this many days (6 days)
retention_week: 21     #Keep weekly backups for this many days (21 days = 3 weeks)
retention_month: 92    #Keep monthly backups for this many days (92 days ~ 3 months)
retention_disk: 7      # keep backups on local disk for this many days

connection_string: "postgres://{{ db_user }}:{{ db_password }}@{{ db_server }}:{{ db_port }}/{{ psql_db }}"

set_backup_cron: true
backup_run_hour: "18" # 18 UTC = 4am AEST; was 23 UTC = 9am AEST
backup_run_minute: "1"

