- hosts: aarnet_db_server
  become: true
  vars_files:
      - group_vars/all.yml
      - group_vars/aarnet.yml
      - group_vars/VAULT
      - group_vars/dbservers.yml
      - host_vars/aarnet-db.usegalaxy.org.au.yml
      - secret_group_vars/stats_server_vault
  pre_tasks:
      - name: Attach volume to instance
        include_role:
          name: attached-volumes
      - name: Install psycopg2 for python3
        apt:
            name: python3-psycopg2
            state: present
        become: true
      - name: stat data directory
        stat:
          path: "{{ postgresql_pgdata }}"
        register: data_directory_stat
      - name: override postgresql_objects_privileges if data directory does not yet exist
        set_fact:
          postgresql_objects_privileges: []
        when: not data_directory_stat.stat.exists
  roles:
      - common
      - insspb.hostname
      - geerlingguy.pip
      - galaxyproject.postgresql
      - move-postgresql-data-directory
      - role: natefoo.postgresql_objects
        become: true
        become_user: postgres
      - dj-wasabi.telegraf
      # Note: After running this playbook for the first time the postgresql services
      # may have stopped with errors due to the moving of the data directory.
      # A reboot should fix this.
