- hosts: aarnet-user-nfs
  become: true
  vars_files:
      - group_vars/all.yml
      - group_vars/aarnet.yml
      - group_vars/VAULT
      - group_vars/nfs_servers.yml
      - host_vars/aarnet-user-nfs.usegalaxy.org.au.yml
  pre_tasks:
      - name: Create galaxy_test_user_data_dir directory
        file:
          path: "{{ galaxy_test_user_data_dir }}"
          state: directory
      - name: Create galaxy_user_data_dir directory
        file:
          path: "{{ galaxy_user_data_dir }}"
          state: directory
      - name: Attach volumes to instance
        include_role:
          name: attached-volumes
  roles:
      - common
      - insspb.hostname
      - geerlingguy.pip
      - geerlingguy.nfs
      - dj-wasabi.telegraf
  post_tasks:
      - name: Chown shared dirs to Galaxy user
        file:
          path: "{{ galaxy_user_data_dir }}"
          owner: galaxy
          group: galaxy
          recurse: yes
      - name: Chown shared dirs to Galaxy user
        file:
          path: "{{ galaxy_test_user_data_dir }}"
          owner: galaxy
          group: galaxy
          recurse: yes
      - name: Reload exportfs
        command: exportfs -ra
        become: yes
        become_user: root
        
