- hosts: dev_handlers_server
  become: true
  vars_files:
    - group_vars/all.yml
    - group_vars/dev.yml # machine_users overridden in this file
    - group_vars/VAULT
    - group_vars/galaxyservers.yml
    - group_vars/dev_slurm.yml
    - host_vars/dev.usegalaxy.org.au.yml
    - host_vars/dev-handlers.usegalaxy.org.au.yml
    - secret_group_vars/ubuntu_maintenance_key
    - secret_group_vars/stats_server_vault
    - secret_group_vars/dev_secrets
    - secret_group_vars/sentry_vault
  handlers:
    - name: galaxy gravity restart
      become: True
      become_user: galaxy
      command: "{{ galaxy_venv_dir }}/bin/galaxyctl graceful"
      environment:
        GRAVITY_STATE_DIR: "{{ galaxy_gravity_state_dir }}"
  pre_tasks:
    - name: create dir for gravity configuration
      file:
        state: directory
        path: /opt/galaxy
        owner: root
        group: galaxy
        mode: 0775
    - name: create dir for galaxy's singularity cache # this is still on the root disk, it's a test of moving the singularity cache
      file:
        state: directory
        path: "{{ galaxy_user_singularity_cachedir }}"
        owner: galaxy
        group: galaxy
        mode: 0700
  roles:
    - galaxyproject.repos
    - common
    - mounts
    #- install-tpv
    #- galaxyproject.postgresql
    #- role: galaxyproject.postgresql_objects
      #become: true
      #become_user: postgres
    - geerlingguy.pip
    - gantsign.golang
    - cyverse-ansible.singularity
    - galaxyproject.galaxy
    #- role: galaxyproject.miniconda
    #  become: true
    #  become_user: galaxy
    #- usegalaxy_eu.galaxy_systemd
    #- nginx-upload-module
    #- galaxyproject.nginx
    #- galaxyproject.tusd
    #- geerlingguy.nfs
    - galaxyproject.slurm
    # - galaxyproject.s3fs
    - galaxyproject.cvmfs
    - galaxyproject.gxadmin
    #- pg-post-tasks
    #- remote-pulsar-cron
    #- galaxy-pg-cleanup
    # - usegalaxy_eu.tiaas2
    #- dev-tiaas2
    #- geerlingguy.docker
    #- usegalaxy_eu.gie_proxy
    - dj-wasabi.telegraf
    #- login-override
    - usegalaxy_eu.flower
    - acl-on-startup
  post_tasks:
    - name: Make local_tool directory group-writable by machine users
      file:
        path: /mnt/galaxy/local_tools
        owner: root
        group: devs
        mode: 0775
        state: directory
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa1

