- hosts: galaxy
  become: true
  vars_files:
    - group_vars/all.yml
    - group_vars/galaxy_etca.yml
    - group_vars/VAULT
    - group_vars/galaxyservers.yml
    - group_vars/galaxy_etca_slurm.yml
    - group_vars/tool_messages.yml
    - host_vars/galaxy.usegalaxy.org.au.yml
    - secret_group_vars/stats_server_vault
    - secret_group_vars/ssh_keys
    - secret_group_vars/etca_vault.yml
  pre_tasks:
    - name: Attach volume to instance
      include_role:
        name: attached-volumes
    - name: Install slurm drmaa ppa
      include_role:
        name: galaxyproject.repos
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa1
        state: latest
    - name: create dir for gravity configuration
      file:
        state: directory
        path: /opt/galaxy
        owner: root
        group: galaxy
        mode: 0775
    - name: Create containing folders for external NFS file mounts
      file:
        state: directory
        path: "{{ item }}"
      with_items:
        - "{{ qld_file_mounts_path }}"
  roles:
    - common
    - mounts
    - geerlingguy.pip
    - galaxyproject.galaxy
    # - role: galaxyproject.miniconda # this role is needed for a fresh installation, but for subsequent playbook runs can take far too much time. TODO: fix this somehow
    #   become: true
    #   become_user: galaxy
    - usegalaxy_eu.galaxy_subdomains
    - role: galaxy_extensions
      tags: extensions
    - nginx-upload-module
    - galaxyproject.nginx
    - galaxyproject.tusd
    - galaxyproject.slurm
    - galaxyproject.cvmfs
    - usegalaxy_eu.apptainer
    - geerlingguy.docker
    - acl-on-startup
    - dj-wasabi.telegraf
    - geerlingguy.nfs
    - galaxyproject.gxadmin
    - postfix-mail-relay
    - remote-pulsar-cron
    # - delete-tmp-jwds-cron # commented out until galaxy etca is production galaxy, also needs to be enabled
    - slg.galaxy_stats
    - galaxy-pg-cleanup
    - galaxyproject.tiaas2
    - role: usegalaxy_eu.walle
      tags: walle
  post_tasks:
    - name: create dir for galaxy's singularity cache
      file:
        state: directory
        path: "{{ item }}"
        owner: galaxy
        group: galaxy
        mode: 0700
      with_items:
        - "{{ galaxy_user_singularity_cachedir }}"
        - "{{ galaxy_user_singularity_tmpdir }}"
    - name: Make local_tool directory group-writable by machine users
      # TODO: This path is problematic because the galaxyproject.galaxy role will chown it to root:root
      # every time we run this playbook, potentially locking out tool devs for 10 minutes.
      # New folder for in /mnt/tools? What would this mean for the lsync? What would this mean for docker volumes?
      file:
        path: "{{ galaxy_root }}/local_tools"
        owner: root
        group: devs
        mode: 0775
        state: directory
    - name: set up lsync between /mnt/galaxy and /mnt/ghost-galaxy-app
      include_role:
        name: lsyncd

    # Nginx logrotate: keep nginx logs forever on /mnt disk
    - name: Make sure extra nginx log dirs exist
      file:
        state: directory
        path: "{{ item }}"
      with_items:
        - "{{ nginx_log_olddir_root }}"
        - "{{ nginx_long_term_log_dir }}"
    - name: Add lines to main block in nginx logrotate conf
      lineinfile:
        path: /etc/logrotate.d/nginx
        line: "{{ item }}"
        insertafter: ".*{"
      with_items:
        - "\tdateext"
        - "\tolddir {{ nginx_log_olddir_root }}"
    - name: Add lines to postrotate task in nginx logrotate conf
      lineinfile:
        path: /etc/logrotate.d/nginx
        line: "{{ item }}"
        insertafter: "\tpostrotate"
      with_items:
        - "\t\tcp -up {{ nginx_log_olddir_root }}/* {{ nginx_long_term_log_dir }}/"
    - name: Create labs engine reporting dir
      ansible.builtin.file:
        path: /home/ubuntu/labs_engine_reporting
        state: directory
        owner: ubuntu
    - name: template script to post nginx logs to the labs engine
      template:
        src: galaxy/scripts/post_labs_logs.sh.j2
        dest: /home/ubuntu/labs_engine_reporting/post_logs.sh
        mode: 0755
        owner: ubuntu
    - name: Setup labs engine reporting cron job
      ansible.builtin.cron:
        name: "labs-engine-reporting"
        minute: "0"
        hour: "6"
        job: "/home/ubuntu/labs_engine_reporting/post_logs.sh > /home/ubuntu/labs_engine_reporting/post_logs.out 2>&1"
