- hosts: galaxy
  become: true
  vars_files:
    - group_vars/all.yml
    - group_vars/galaxy_etca.yml
    - group_vars/VAULT
    - group_vars/galaxyservers.yml
    - group_vars/galaxy_etca_slurm.yml
    - host_vars/galaxy.usegalaxy.org.au.yml
    - secret_group_vars/stats_server_vault
    - secret_group_vars/ubuntu_maintenance_key
  pre_tasks:
    - name: Attach volume to instance
      include_role:
        name: attached-volumes
    - name: Install slurm drmaa ppa
      include_role:
        name: galaxyproject.repos
    - name: Install slurm-drmaa
      package:
        name: slurm-drmaa1
        state: latest
  roles:
    - common
    - install-tpv
    - mounts
    - geerlingguy.pip
    - galaxyproject.galaxy
    - role: galaxyproject.miniconda
      become: true
      become_user: galaxy
    - nginx-upload-module
    - galaxyproject.nginx
    - galaxyproject.tusd
    - galaxyproject.slurm
    - galaxyproject.cvmfs
    # - gantsign.golang
    # - cyverse-ansible.singularity
    - usegalaxy_eu.apptainer # see how this works as replacement for golang+cyverse/singularity
    - geerlingguy.docker
    - acl-on-startup
    # - dj-wasabi.telegraf # TODO: switch on once influx has tables
    - galaxyproject.gxadmin
    - usegalaxy_eu.gie_proxy
    - pg-post-tasks
    # - remote-pulsar-cron # commented out until galaxy etca is production galaxy
    # - delete-tmp-jwds-cron # commented out until galaxy etca is production galaxy, also needs to be enabled
    # - slg.galaxy_stats # commented out until galaxy etca is production galaxy
    - galaxy-pg-cleanup
    - galaxyproject.tiaas2
  post_tasks:
    - name: create dir for galaxy's singularity cache
      file:
        state: directory
        path: "{{ item }}"
        owner: galaxy
        group: galaxy
        mode: 0700
      with_items:
        - "{{ galaxy_user_singularity_cachedir }}"
        - "{{ galaxy_user_singularity_tmpdir }}"
    - name: create dir for galaxy's custom indices  # TODO: directory creation is not needed here once /mnt/custom-indices exists on galaxy-misc-nfs
      file:
        state: directory
        path: "{{ galaxy_custom_indices_dir }}"
        owner: galaxy
        group: galaxy
    - name: Make local_tool directory group-writable by machine users
      # TODO: This path is problematic because the galaxyproject.galaxy role will chown it to root:root
      # every time we run this playbook, potentially locking out tool devs for 10 minutes.
      # New folder for in /mnt/tools? What would this mean for the lsync? What would this mean for docker volumes?
      file:
        path: "{{ galaxy_root }}/local_tools"
        owner: root
        group: devs
        mode: 0775
        state: directory
    - name: Uninstall the existing web-dav-client  # TODO: these two tasks could be a role
      pip:
        name: "webdavclient3"
        virtualenv: "{{ galaxy_venv_dir }}"
        state: absent
    - name: Workaround content-length header bug in webdav through update to newer version
      pip:
        name: "webdavclient3@git+https://github.com/ezhov-evgeny/webdav-client-python-3@0f17fa7946e66f7963db367d0d6b2e7f940ebeb8"
        virtualenv: "{{ galaxy_venv_dir }}"
    - name: setup lsyncd
      # TODO: (a) This could be a role,
      # (b) there is no need to sync all of /mnt/galaxy: only /mnt/galaxy/galaxy-app and /mnt/galaxy/venv need to exist for the workers
      # Possible /mnt/galaxy/local_tools also needs to exist for the workers. Move that dir into /mnt/tools?
      package:
        name: lsyncd
        state: present
    - name: create lsync dirs
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /etc/lsyncd
        - /var/log/lsyncd
    - name: config lsyncd
      copy:
        src: lsyncd/lsyncd.conf.lua
        dest: /etc/lsyncd/lsyncd.conf.lua
      become: yes
    - name: Set max_user_watches
      command: sysctl fs.inotify.max_user_watches=524288
      become: true
    - name: restart lsyncd
      systemd:
        name: lsyncd
        state: restarted
