- hosts: staging_galaxy_server
  become: true
  vars_files:
      - group_vars/all.yml
      - group_vars/staging.yml
      - group_vars/VAULT
      - group_vars/galaxyservers.yml
      - group_vars/staging_slurm.yml
      - host_vars/staging.usegalaxy.org.au.yml
      - secret_group_vars/ubuntu_maintenance_key
  vars:
    - tpv_files:
      - vortex_config.yml
  handlers:
    - name: galaxy gravity restart
      become: True
      become_user: galaxy
      command: "{{ galaxy_venv_dir }}/bin/galaxyctl graceful"
      environment:
        GRAVITY_STATE_DIR: "{{ galaxy_root }}/gravity"
  pre_tasks:
    - name: copy job_conf file
      template:
        src: "{{ galaxy_config_template_src_dir }}/config/staging_job_conf.yml.j2"
        dest: "{{ galaxy_config_dir }}/job_conf.yml"
      notify: galaxy gravity restart
    - name: Copy tpv files to staging
      copy:
        src: "files/galaxy/dynamic_job_rules/staging/total_perspective_vortex/{{ item }}"
        dest: "{{ galaxy_dynamic_job_rules_dir }}/total_perspective_vortex/{{ item }}"
      with_items: "{{ tpv_files }}"
