global:
  default_inherits: default

tools:
  default:
    cores: 1
    mem: cores * 3.8
    env: {}
    params:
      nativeSpecification: "--nodes=1 --ntasks={cores} --ntasks-per-node={cores} --mem={round(mem*1024)}"
      submit_native_specification: "--nodes=1 --ntasks={cores} --ntasks-per-node={cores} --mem={round(mem*1024)}"
      docker_memory: '{mem}G'
    scheduling:
      reject:
        - offline
    rules: []
    rank: |
      final_destinations = helpers.weighted_random_sampling(candidate_destinations)
      final_destinations
  upload1:
    cores: 1
  toolshed.g2.bx.psu.edu/repos/iuc/fastqe/fastqe/.*:
    cores: 2
  toolshed.g2.bx.psu.edu/repos/bgruening/bionano_scaffold/bionano_scaffold/.*:
    params:
      docker_enabled: true
  toolshed.g2.bx.psu.edu/repos/bgruening/autodock_vina/docking/.*:
    params:
      singularity_enabled: true
  toolshed.g2.bx.psu.edu/repos/bgruening/chemfp/ctb_chemfp_nxn_clustering/.*:
    params:
      singularity_enabled: true
  toolshed.g2.bx.psu.edu/repos/bgruening/chemfp/ctb_chemfp_mol2fps/.*:
    params:
      singularity_enabled: true
  toolshed.g2.bx.psu.edu/repos/bgruening/chemfp/ctb_sdf2fps/.*:
    params:
      singularity_enabled: true
  toolshed.g2.bx.psu.edu/repos/bgruening/chemfp/ctb_chemfp_butina_clustering/.*:
    params:
      singularity_enabled: true

destinations:
  slurm:
    cores: 4
    mem: 15.5
    scheduling:
      accept:
        - pulsar
        - slurm
  pulsar:
    cores: 4
    mem: 7.77
    scheduling:
      accept:
        - staging-pulsar
      require:
        - pulsar

users:
  jenkins_bot@usegalaxy.org.au:
    cores: 1
    scheduling:
      require:
        - slurm