- type: webdav
  id: cloudstor
  label: CloudStor
  doc: Import your files from CloudStor. Configure access in User -> Preferences -> Manage Information
  url: "https://cloudstor.aarnet.edu.au"
  root: "/plus/remote.php/webdav"
  login: ${user.preferences['owncloud_account|username']}
  password: ${user.preferences['owncloud_account|password']}
  writable: true

- type: webdav
  id: griffith_owncloud
  label: Griffith Owncloud
  doc: Import your files from CloudStor. Configure access in User -> Preferences -> Manage Information
  url: "https://research-storage.griffith.edu.au/owncloud"
  root: "/remote.php/nonshib-webdav"
  login: ${user.preferences['griffith_owncloud_account|username']}
  password: ${user.preferences['griffith_owncloud_account|password']}
  writable: true

- type: dropbox
  id: dropbox
  label: Dropbox
  doc: Your Dropbox files. Configure your access token via User -> Preferences -> Manage Information
  accessToken: ${user.preferences['dropbox|access_token']}

- type: s3fs
  label: Genome Ark
  id: genomeark
  doc: Access to Genome Ark open data on AWS.
  bucket: genomeark
  anon: true

- type: s3fs
  label: 1000 Genomes
  id: 1000genomes
  doc: Access to the 1000 Genomes Project with human genetic variation, including SNPs, structural variants, and their haplotype context.
  bucket: 1000genomes
  anon: true

- type: s3fs
  label: The Cancer Genome Atlas
  id: tcga-2-open
  doc: Access to the Cancer Genome Atlas (TCGA)
  bucket: tcga-2-open
  anon: true

- type: s3fs
  label: COVID-19 Data Lake
  id: covid19-lake
  doc: A centralized repository of up-to-date and curated datasets on or related to the spread and characteristics of the novel corona virus (SARS-CoV-2) and its associated illness, COVID-19
  bucket: covid19-lake
  anon: true

- type: s3fs
  label: Encyclopedia of DNA Elements (ENCODE)
  id: encode-public
  doc: The Encyclopedia of DNA Elements (ENCODE) Consortium is an international collaboration of research groups funded by the National Human Genome Research Institute (NHGRI)
  bucket: encode-public
  anon: true
