# attached_volumes
attached_volumes:
  - device: /dev/vdc
    path: /mnt
    fstype: ext4

# common
create_ssh_key: yes  # Only the first time.
ssl_country: "AU"
ssl_state: "ACT"
ssl_location: "Canberra"
ssl_organisation: "Galaxy Australia"
ssl_operational_unit: "Pulsar NCI Training"
ssl_email: "help@genome.edu.au"

add_hosts_workers: yes

hostname: "{{ ansible_hostname }}.usegalaxy.org.au"

extra_keys:
  - id: ubuntu_maintenance_key
    type: public
    from: "{{ hostvars['galaxy']['ansible_ssh_host'] }},{{ hostvars['galaxy-handlers']['ansible_ssh_host'] }},{{ hostvars['galaxy-backup']['ansible_ssh_host'] }}"
  - id: pulsar_internal_hop_key
    type: private

ssh_config_entries:
- id_file: "/home/ubuntu/.ssh/pulsar_internal_hop_key"
  user: ubuntu
  hosts: "{{ groups['pulsar_nci_training_workers'] }}"

# geerlingguy.nfs
nfs_exports:
    - "{{ pulsar_custom_indices_dir }}  10.0.0.0/22(rw,async,no_root_squash,no_subtree_check)"
    - "/mnt/pulsar  10.0.0.0/22(rw,async,no_root_squash,no_subtree_check)"

# galaxyproject.pulsar
rabbitmq_password_galaxy_au: "{{ vault_rabbitmq_password_galaxy_nci_training_prod }}"
pulsar_queue_url: "galaxy-queue.usegalaxy.org.au"
pulsar_rabbit_username: "galaxy_nci_training"
pulsar_rabbit_vhost: "/pulsar/galaxy_nci_training"

# geerlingguy.docker
docker_daemon_options:
  data-root: /mnt/docker-data
