attached_volumes:
  # - device: /dev/vdb
  #   path: /mnt  # this will contain user-data, user-data-2/3/4 from perth.  
  #   fstype: ext4

# galaxy_nfs_user_data_dir: /mnt/user-data
# galaxy_nfs_user_data_2_dir: /mnt/user-data-2
# galaxy_nfs_user_data_3_dir: /mnt/user-data-3
# galaxy_nfs_user_data_4_dir: /mnt/user-data-4
# galaxy_nfs_user_data_5_dir: /mnt/user-data-5  # new data path

nfs_exports:
  # - "{{ galaxy_nfs_user_data_dir }} {{ hostvars['aarnet'].internal_ip.split('.')[:-1] | join('.') }}.0/24(rw,async,no_root_squash,no_subtree_check)"
  # - "{{ galaxy_nfs_user_data_2_dir }} {{ hostvars['aarnet'].internal_ip.split('.')[:-1] | join('.') }}.0/24(rw,async,no_root_squash,no_subtree_check)"
  # - "{{ galaxy_nfs_user_data_3_dir }} {{ hostvars['aarnet'].internal_ip.split('.')[:-1] | join('.') }}.0/24(rw,async,no_root_squash,no_subtree_check)"
  # - "{{ galaxy_nfs_user_data_4_dir }} {{ hostvars['aarnet'].internal_ip.split('.')[:-1] | join('.') }}.0/24(rw,async,no_root_squash,no_subtree_check)"
  # - "{{ galaxy_nfs_user_data_5_dir }} {{ hostvars['aarnet'].internal_ip.split('.')[:-1] | join('.') }}.0/24(rw,async,no_root_squash,no_subtree_check)"
