aarnet_dev_galaxy_server_address: "{{ hostvars['aarnet-dev']['internal_ip'] }}/32"

postgresql_conf:
  # Postgresql settings from: https://pgtune.leopard.in.ua/#/ - recommended by @natefoo.
  # Input settings:
  # DB Version: 12
  # OS Type: linux
  # DB Type: web
  # Total Memory (RAM): 8 GB
  # CPUs num: 4
  # Connections num: 100
  # Data Storage: san

  - max_connections: 100
  #- shared_buffer: 2GB #### - not a valid parameter
  - effective_cache_size: 6GB
  - maintenance_work_mem: 512MB
  - checkpoint_completion_target: 0.7
  - wal_buffers: 16MB
  - default_statistics_target: 100
  - random_page_cost: 1.1
  - effective_io_concurrency: 300
  - work_mem: 10485kB
  - min_wal_size: 1GB
  - max_wal_size: 4GB
  - max_worker_processes: 4
  - max_parallel_workers_per_gather: 2
  - max_parallel_workers: 4
  - max_parallel_maintenance_workers: 2
  - listen_addresses: "'*'"   # Allow remote connections

postgresql_pgdata: "/data/production"

postgresql_pg_hba_conf:
  - host all all "{{ aarnet_dev_galaxy_server_address }}" md5 #The allowed connection to the database for the dev galaxy server.

postgresql_objects_users:
  - name: galaxy
    password: "{{ galaxy_dev_db_user_password }}"
    db: galaxy
    priv: "ALL"
  - name: reader
    password: "{{ vault_aarnet_dev_db_reader_password }}"
    db: galaxy
  - name: tiaas
    password: "{{ tiaas_galaxy_db_password }}"
postgresql_objects_privileges:
  - database: galaxy
    roles: reader
    objs: ALL_IN_SCHEMA
    privs: SELECT
  - database: galaxy
    roles: tiaas
    objs: galaxy_user,galaxy_session,job,history,workflow,workflow_invocation
    type: table
    privs: SELECT
  - database: galaxy
    roles: tiaas
    objs: user_group_association,galaxy_group,role,group_role_association
    type: table
    privs: SELECT,INSERT
  - database: galaxy
    roles: tiaas
    objs: role_id_seq,galaxy_group_id_seq,group_role_association_id_seq,user_group_association_id_seq
    type: sequence
    privs: USAGE,SELECT
postgresql_objects_databases:
  - name: galaxy
    owner: galaxy

galaxy_dev_db_user_password: "{{ vault_aarnet_dev_db_user_password }}"

attached_volume_device: /dev/vdb
attached_volume_fstype: ext4
attached_volume_path: /data