# Keys and shares

create_ssh_key: yes  # Only the first time.
ssl_country: "AU"
ssl_state: "VIC"
ssl_location: "Melbourne"
ssl_organisation: "Galaxy Australia"
ssl_operational_unit: "Pulsar Dev"
ssl_email: "help@genome.edu.au"

#host specific pulsar settings

rabbitmq_password_galaxy_au: "{{ vault_rabbitmq_password_galaxy_au_dev }}"
pulsar_queue_url: "dev-queue.usegalaxy.org.au"
pulsar_rabbit_username: "galaxy_au"
pulsar_rabbit_vhost: "/pulsar/galaxy_au"

pulsar_conda_exec: "mamba"  # Use mamba as replacement for conda

extra_keys:
  - id: ubuntu_maintenance_key
    type: public
    from: "{{ hostvars['dev']['ansible_ssh_host'] }}"

# Docker
docker_install_compose: false
docker_users:
  - "{{ pulsar_user.name }}"

# acl-on-startup role
acl_job_runner_user: "{{ pulsar_user.name }}"
