hostname: "{{ ansible_hostname }}.usegalaxy.org.au"

# Keys and shares

create_ssh_key: yes  # Only the first time.
ssl_country: "AU"
ssl_state: "Qld"
ssl_location: "Brisbane"
ssl_organisation: "Galaxy Australia"
ssl_operational_unit: "Pulsar Qld GPU3"
ssl_email: "help@genome.edu.au"

#host specific pulsar settings

rabbitmq_password_galaxy_au: "{{ vault_rabbitmq_password_galaxy_qldgpu3_prod }}"
pulsar_rabbit_username: "galaxy_qldgpu3"
pulsar_rabbit_vhost: "/pulsar/galaxy_qldgpu3"