hostname: "{{ ansible_hostname }}.usegalaxy.org.au"

# Keys and shares

create_ssh_key: yes  # Only the first time.
ssl_country: "AU"
ssl_state: "Qld"
ssl_location: "Brisbane"
ssl_organisation: "Galaxy Australia"
ssl_operational_unit: "Pulsar Qld blast"
ssl_email: "help@genome.edu.au"

#host specific pulsar settings

rabbitmq_password_galaxy_au: "{{ vault_rabbitmq_password_galaxy_qld_blast_prod }}"
pulsar_queue_url: "pawsey-queue.usegalaxy.org.au"
pulsar_rabbit_username: "galaxy_qld_blast"
pulsar_rabbit_vhost: "/pulsar/galaxy_qld_blast"


galaxy_uid: 10010
galaxy_gid: 10010

use_internal_ips: false

# cvmfs
cvmfs_cache_base: /mnt/var/lib/cvmfs
cvmfs_quota_limit: 410000

#Monitoring for Staging. Once all VM monitoring has moved to stats.usegalaxy.org.au, this can be put in all.yml and removed here.
influx_url: stats.usegalaxy.org.au
grafana_server_url: "https://{{ influx_url }}:8086"

# Monitoring
telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["{{ grafana_server_url }}"]
      - database = "pulsar-special"
      - precision = "s"
      - username = "node"
      - password = "{{ vault_influx_node_password }}"

auth_key_user: ubuntu

head_nodes: "{{ groups['pulsar_qld_blast'] }}"

# SLURM
slurm_nodes:
    - name: pulsar-qld-blast
      NodeAddr: "{{ hostvars['pulsar-qld-blast']['ansible_ssh_host'] }}"
      CPUs: 60
      RealMemory: 200000
      State: UNKNOWN

slurm_partitions:
    - name: main
      nodes: "pulsar-qld-blast"
      Default: YES
      MaxTime: INFINITE
      State: UP

slurm_config:
    #SlurmDBd includes
    AccountingStorageType: accounting_storage/slurmdbd
    AccountingStorageHost: localhost
    JobAcctGatherType: jobacct_gather/linux
    ControlMachine: pulsar-qld-blast
    SlurmctldPidFile: /run/slurmctld.pid
    SlurmdPidFile: /run/slurmd.pid
    # SCHEDULING
    FastSchedule: 2
    SchedulerType: sched/backfill
    SelectType: select/cons_res
    SelectTypeParameters: CR_CPU_Memory,CR_LLN

slurm_munge_key: files/keys/munge.key

extra_keys:
  - id: ubuntu_maintenance_key
    type: public
    from: "{{ hostvars['pawsey']['ansible_ssh_host'] }}"
