# Keys and shares

create_ssh_key: yes  # Only the first time.
ssl_country: "AU"
ssl_state: "VIC"
ssl_location: "Melbourne"
ssl_organisation: "Galaxy Australia"
ssl_operational_unit: "Pulsar Staging"
ssl_email: "help@genome.edu.au"

#host specific pulsar settings

rabbitmq_password_galaxy_au: "{{ vault_rabbitmq_password_galaxy_au_staging }}"
pulsar_queue_url: "staging-queue.gvl.org.au"
pulsar_rabbit_username: "galaxy_au"
pulsar_rabbit_vhost: "/pulsar/galaxy_au"

pulsar_conda_exec: "mamba"  # Use mamba as replacement for conda
