---

- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: install cerbot
  ansible.builtin.apt:
    name: certbot
    state: present
  tags: always

- name: Docker pull labs-engine image
  ansible.builtin.docker_image:
    name: "{{ labs_engine_docker_image }}"
    source: pull
    force_source: yes  # Ensures it re-checks the remote registry
    state: present
  tags: update

- name: clone git repository for galaxy-labs-engine
  ansible.builtin.git:
    repo: "{{ labs_engine_repo }}"
    version: "{{ labs_engine_branch }}"
    dest: "{{ project_root }}"
    clone: yes
    force: yes
    update: yes
  tags: always
  register: git

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ create_directories }}"
  tags: config

- name: check if SSL certificate is installed
  stat:
    path: /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem
  register: certbot_certificates
  tags:
    - config
    - certbot

- name: obtain initial SSL certificate with certbot
  include_tasks: certbot.yml
  when: certbot_ssl and certbot_certificates.stat.exists is false
  tags: certbot

- name: template webserver configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ labs_engine.templates }}"
  tags:
    - config
    - certbot

- name: copy webserver configuration
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ labs_engine.files }}"
  tags: config

- name: Set media file ownership
  file: dest={{ django_root }}/app/media owner=www-data group=www-data mode=u=rwX,g=rwX,o=rwX recurse=yes
  tags:
    - permissions
    - update

- name: Set log file ownership
  file: dest={{ django_root }}/app/logs owner=www-data group=www-data mode=u=rwX,g=rwX,o=rwX recurse=yes
  tags:
    - permissions
    - update

- name: Update sqlite3 database ownership
  file: dest={{ django_root }}/db.sqlite3 owner=www-data group=www-data mode=u=rw,g=rw,o=r
  tags:
    - permissions
  ignore_errors: yes

- name: Update sqlite3 database directory permissions
  file:
    dest: "{{ django_root }}"
    owner: root
    group: www-data
    mode: u=rwx,g=rwx,o=rx
  tags:
    - permissions

- name: Django create django_cache table with 'manage.py createcachetable'
  shell: >
    docker compose --profile prod run --rm labs-engine
    python manage.py createcachetable
  args:
    chdir: "{{ config_root }}"
  tags: django

- name: Django run migrations
  shell: >
    docker compose --profile prod run --rm
    labs-engine
    python manage.py migrate
  args:
    chdir: "{{ config_root }}"
  when: not skip_database_migration
  tags:
    - django
    - update

- name: Django collect static files
  shell: >
    docker compose --profile prod run --rm --user root
    labs-engine
    python manage.py collectstatic --noinput
  args:
    chdir: "{{ config_root }}"
  tags: always

- name: Django ensure superuser login
  shell: >
    docker compose --profile prod run --rm
    -e DJANGO_SUPERUSER_PASSWORD={{ admin_user.password }}
    labs-engine
    python manage.py createsuperuser --noinput
    --email {{ admin_user.email }}
    --first_name {{ admin_user.first_name }}
    --last_name {{ admin_user.last_name }}
  args:
    chdir: "{{ config_root }}"
  ignore_errors: yes
  when: admin_user.email and not skip_database_migration
  tags:
    - init
    - django

- name: Django clear cache
  shell: >
    docker compose --profile prod run --rm
    labs-engine
    python manage.py shell -c
    "from django.core.cache import cache; cache.clear()"
  args:
    chdir: "{{ config_root }}"
  tags: clear_cache

- name: enable labs_engine socket
  ansible.builtin.systemd:
    name: labs_engine.socket
    enabled: yes
    state: started
  tags: init

- name: Run systemctl daemon-reload
  ansible.builtin.command: "systemctl daemon-reload"
  become: yes
  tags: config

- name: Enable and restart labs_engine service
  ansible.builtin.systemd:
    name: labs_engine
    enabled: yes
    state: restarted
  tags: always
