---

- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: install cerbot
  ansible.builtin.apt:
    name: certbot
    state: present
  tags: always

- name: Docker pull labs-engine image
  ansible.builtin.docker_image:
    name: "{{ labs_engine_docker_image }}"
    source: pull
    force_source: yes  # Ensures it re-checks the remote registry
    state: present
  tags: update
  notify: update labs cache

- name: clone git repository for galaxy-labs-engine
  ansible.builtin.git:
    repo: "{{ labs_engine_repo }}"
    version: "{{ labs_engine_branch }}"
    dest: "{{ labs_project_root }}"
    clone: yes
    force: yes
    update: yes
  tags: always
  notify: update labs cache

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ labs_create_directories }}"
  tags: config

- name: check if SSL certificate is installed
  stat:
    path: /etc/letsencrypt/live/{{ labs_domain_name }}/fullchain.pem
  register: certbot_certificates
  tags:
    - config
    - certbot

- name: obtain initial SSL certificate with certbot
  include_tasks: certbot.yml
  when: labs_certbot_ssl and certbot_certificates.stat.exists is false
  tags: certbot

- name: template webserver configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ labs_engine.templates }}"
  tags:
    - config
    - certbot

- name: copy webserver configuration
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ labs_engine.files }}"
  tags: config

- name: Update labs_project_root directory permissions
  file: dest={{ labs_project_root }} mode=u=rwX,g=rwX,o=rX recurse=yes
  tags:
    - permissions
    - update

- name: Update labs_config_root directory permissions
  file: dest={{ labs_config_root }} mode=u=rwX,g=rwX,o=rX recurse=yes
  tags:
    - permissions
    - update

- name: Set media file ownership
  file: dest={{ labs_django_root }}/media owner=www-data group=www-data mode=u=rwX,g=rwX,o=rwX recurse=yes
  tags:
    - permissions
    - update

- name: Set log file ownership
  file: dest={{ labs_django_root }}/logs owner=www-data group=www-data mode=u=rwX,g=rwX,o=rwX recurse=yes
  tags:
    - permissions
    - update

- name: Set temp dir permissions
  file: dest={{ labs_temp_dir }} mode=u=rwX,g=rwX,o=rwX
  tags:
    - permissions
    - update

- name: Update sqlite3 database ownership
  file: dest={{ labs_django_root }}/db.sqlite3 owner=www-data group=www-data mode=u=rw,g=rw,o=r
  tags:
    - permissions
  ignore_errors: true

- name: Update sqlite3 database directory permissions
  file:
    dest: "{{ labs_django_root }}"
    owner: root
    group: www-data
    mode: u=rwx,g=rwx,o=rx
  tags:
    - permissions

- name: Django create django_cache table with 'manage.py createcachetable'
  shell: >
    docker compose --profile prod run --rm labs-engine
    python manage.py createcachetable
  args:
    chdir: "{{ labs_config_root }}"
  tags: django

- name: Django run migrations
  shell: >
    docker compose --profile prod run --rm labs-engine
    python manage.py migrate
  args:
    chdir: "{{ labs_config_root }}"
  tags:
    - django
    - update
    - migrate

- name: Django collect static files
  shell: >
    docker compose --profile prod run --rm --user root labs-engine
    python manage.py collectstatic --noinput
  args:
    chdir: "{{ labs_config_root }}"
  tags: always

- name: Django ensure superuser login
  shell: >
    docker compose --profile prod run --rm
    -e DJANGO_SUPERUSER_PASSWORD={{ labs_admin_user.password }}
    labs-engine
    python manage.py createsuperuser --noinput
    --email {{ labs_admin_user.email }}
    --first_name {{ labs_admin_user.first_name }}
    --last_name {{ labs_admin_user.last_name }}
  args:
    chdir: "{{ labs_config_root }}"
  ignore_errors: true
  when: labs_admin_user.email
  tags:
    - init
    - django

- name: Run systemctl daemon-reload
  ansible.builtin.command: "systemctl daemon-reload"
  become: true
  tags: config

- name: Ensure that system Nginx is not running
  ansible.builtin.systemd:
    name: nginx
    enabled: no
    state: stopped
  tags: always
  ignore_errors: true

- name: Stop labs_engine service
  ansible.builtin.systemd:
    name: labs_engine
    enabled: yes
    state: stopped
  tags: always

- name: Clean up zombie containers
  shell: |
    docker rm -f $(docker ps -a -q) || true
  tags: always

- name: Enable and restart labs_engine service
  ansible.builtin.systemd:
    name: labs_engine
    enabled: yes
    state: restarted
  tags: always
