auth_key_user: ubuntu

head_nodes: "{{ groups['pulsar_mel3_head'] }}"
worker_nodes: "{{ groups['pulsar_mel3_workers'] }}"

# SLURM
slurm_nodes:
  - name: pulsar-mel3
    NodeAddr: "{{ hostvars['pulsar-mel3']['ansible_ssh_host'] }}"
    CPUs: 8
    RealMemory: 32116
    State: UNKNOWN
  - name: pulsar-mel3-w1
    NodeAddr: "{{ hostvars['pulsar-mel3-w1']['ansible_ssh_host'] }}"
    CPUs: 16
    RealMemory: 64419
    State: UNKNOWN
  - name: pulsar-mel3-w2
    NodeAddr: "{{ hostvars['pulsar-mel3-w2']['ansible_ssh_host'] }}"
    CPUs: 16
    RealMemory: 64419
    State: UNKNOWN
  - name: pulsar-mel3-w3
    NodeAddr: "{{ hostvars['pulsar-mel3-w3']['ansible_ssh_host'] }}"
    CPUs: 32
    RealMemory: 125812
    State: UNKNOWN
  - name: pulsar-mel3-w4
    NodeAddr: "{{ hostvars['pulsar-mel3-w4']['ansible_ssh_host'] }}"
    CPUs: 32
    RealMemory: 125812
    State: UNKNOWN
  - name: pulsar-mel3-w5
    NodeAddr: "{{ hostvars['pulsar-mel3-w5']['ansible_ssh_host'] }}"
    CPUs: 32
    RealMemory: 125812
    State: UNKNOWN
  - name: pulsar-mel3-w6
    NodeAddr: "{{ hostvars['pulsar-mel3-w6']['ansible_ssh_host'] }}"
    CPUs: 16
    RealMemory: 64419
    State: UNKNOWN

slurm_partitions:
  - name: main
    nodes: "pulsar-mel3-w1,pulsar-mel3-w2,pulsar-mel3-w3,pulsar-mel3-w4,pulsar-mel3-w5,pulsar-mel3-w6"
    Default: YES
    MaxTime: INFINITE
    State: UP

slurm_controller_host: pulsar-mel3

slurm_munge_key: files/keys/munge.key
